# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Bajra Weekly
tagline:             '- Keep Calm and Keep Blogging'
description:         'Bajra Weekly'
url:                 http://bajratechnologies.com
baseurl:             ''
gems: [jekyll-paginate]
paginate: 5
paginate_path: "page:num"
tag_page_layout: tag_page
tag_page_dir: tag
tag_permalink_style: pretty

# About/contact
author:
  name:              Bajra Technologies
  url:               http://bajratechnologies.com
  email:             admin@bajratechnologies.com

# Custom vars
version:             1.0.0

pages_list:
  About: '/about'
  Archive: '/archive'
  Feed: '/atom.xml'
