# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Bajra Weekly
tagline:             '- Keep Calm and Blog On'
description:         'Bajra Weekly'
url:                 http://blog.bajratechnologies.com
baseurl:             ''
gems: 
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll/tagging
paginate: 5
paginate_path: "page:num"
tag_page_layout: tag_page
tag_page_dir: tag
tag_permalink_style: pretty

facebook:
  app_id: 182586012174142

# About/contact
author:
  name:              Bajra Technologies
  url:               http://blog.bajratechnologies.com
  email:             admin@bajratechnologies.com

# Custom vars
version:             1.0.0

pages_list:
  About: '/about'
  Archive: '/archive'
  Feed: '/atom.xml'
